spring.datasource.url=jdbc:postgresql://localhost:5432/school-console-app
spring.datasource.username=postgres
spring.datasource.password=0403
spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.active=spring-data-jpa
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate