#spring.datasource.url=jdbc:tc:postgresql:///school-console-app
spring.datasource.url=jdbc:postgresql://localhost:5432/school-console-app
spring.datasource.username=postgres
spring.datasource.password=0403
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.profiles.active=spring-jdbc